### ISSUE TITLE
1080p not showing?

### ISSUE THREAD

**Issue by stephanembl** [pytube/pytube#106]
Hi. Thank you for this awesome library.

It appears that 1080p quality never shows up as an option even though it's available on YouTube. Is it a choice (I admit I haven't looked at the source) or an unwanted behavior?

Thanks!

**Comment by nficano** [comment]
thanks, let me take a look!

**Comment by ghost** [comment]
The maximum quality available is 720p... No higher than that (tested with 2160p videos). Also, no option for 720p 60fps or 1080p 60fps. I think it's some kind of limit? I am not sure if it was made by nficano on purpose. But still, I enjoy it. I'm newbie at Python and GitHub.. It keeps me kinda hooked :)

**Comment by dyeray** [comment]
Videos of more than 720p only seem to be available from YouTube by using Media Source Extensions (so they are served as a stream from a javascript API instead of a link to a file). This may be related.

https://googlesystem.blogspot.com/2013/10/youtube-drops-support-for-1080p-streams.html

**Comment by nficano** [comment]
Interesting find, I looked into this the other day, I assumed the quality profiles needed to be updated:
https://github.com/nficano/pytube/commit/d625b83f2c2af9afde3fc1c3358662f232de0143

(fwiw these have historically been maintained here: https://en.wikipedia.org/wiki/YouTube#Quality_and_formats) 

But this doesn't seem to fix it. I'm going to poke around similar projects see how they have addressed this, I'll try to have an update today.

**Comment by Cg-boy** [comment]
Hi.
Is there any progress on getting 1080p to work yet? This is a great library, and I'd like to use it for a youtube downloader I'm working on, but it would be nice to be able to download 1080p videos.

Thanks.

**Comment by piratimir** [comment]
@Cg-boy I am currently working on this issue :)

**Comment by Cg-boy** [comment]
@jetbird Okay, thanks.

**Comment by piratimir** [comment]
I have been hacking the code  and I see the 1080p quality video link is not being included in the url_encoded_fmt_stream_map. There is a way to get the separate streams and then join them using ffmpeg. I am ready to implement this feature if @nficano agrees.

**Comment by piratimir** [comment]
@nficano I pushed the code for solving this issue and also created a PR.

**Comment by nficano** [comment]
thanks will merge today

**Comment by andreif** [comment]
Related PR is #136

**Comment by Chandrahasabburi** [comment]
i think 1080p issue is still not solved.  Any leads on this topic ?

**Comment by amir3code** [comment]
1080 and 2160 are not showing. Your project is not complete

**Comment by myelmer** [comment]
Is there anything about 1080p?

**Comment by ghost** [comment]
Video quality 720p+ (even 4k) are available using **adaptive_fmts** instead of **url_encoded_fmt_stream_map**, BUT, video is separated from audio.

**Comment by nficano** [comment]
@myelmer @svkboii I been working hard over the past 2 weeks to do a complete rewrite of pytube (available here: https://github.com/nficano/pytube/tree/7.0.0). 

I'm in the burn down phase of getting it releasable, the outstanding tasks are:
- [ ] comments and docstrings
- [ ] unit tests
- [ ] exceptions
- [ ] update readme

This release finally exposes ``adaptive_fmts`` which includes the 1080p stream.

**Comment by ghost** [comment]
Basically, I am working on my own YouTube downloader. I am working on it two days now (yesterday I was doing some research) and I started programming today. I have my own signature function extractor + all video data. Now I am working on the UI. Higher quality videos will be downloaded from dash streams (adaptive_fmts) and video+audio merged using ffmpeg.

**Comment by Igorjan94** [comment]
Is 60fps and 1080p working now properly?  
```
$ pytube "http://youtube.com/watch?v=spDvpDGVNTA" -l
<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2">
<Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">
<Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">
<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">
```

```
$ pytube --version                                                 
pytube 9.1.1
```

But we can see, that video contains 720p60 and 1080p60

**Comment by PathToLife** [comment]
^ Can confirm that 1080p60fps videos aren't showing.

**Comment by alejandroch1202** [comment]
Was this solve?

**Comment by PathToLife** [comment]
@alejandroch1202

Just running the latest version on igorjan94's post, seems 1080p60fps is still not showing.

```
pytube "http://youtube.com/watch?v=<igorjan94's post>" -l
Loading video...
<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="10fps" vcodec="mp4v.20.3" acodec="mp4a.40.2" progressive="True" type="video">
<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">
<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2" progressive="True" type="video">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">
<Stream: itag="139" mime_type="audio/mp4" abr="48kbps" acodec="mp4a.40.5" progressive="False" type="audio">
<Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">
<Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">
```

```
pytube --version
pytube 15.0.0
```

**Comment by jomartla** [comment]
As @PathToLife said, it seems that 1080p is not among the video streams. I tried:

- YouTube(video_link).video.streams.filter(adaptive=False)
- YouTube(video_link).video.streams.filter(adaptive=True)

None of them are returning a 1080p stream. Any idea what could be happening? 

Thank you in advance

**Comment by Dave-Ed-Castaldi** [comment]
To be honest there is a workaround for getting 1080p but it only works with some videos. For instance, let's say you want to download a 1080p video that is originally 4k. When you try to download it, it just doesn't work. But when the upper limit of the video hits 1080p, then the downloader gets it.

This has been made possible by simply: `yt.streams.filter(res = "1080p").first().download(path)`

Of course this only works on certain conditions so I think the only possible way right now is by merging through ffmpeg

**Comment by tenix7676** [comment]
bruh, why can I only download int shitty quality :(((

Edit: I came to realise that youtube gives quality audio and quality videos, separately and they can later be merged to get great quality videos

**Comment by Jopro1990** [comment]
I have solved the issue for 1080p (at least in my code), I am able to download 2160p, 1440p and 1080p videos as long as they are not 1080p60 (and 1440p60, 2160p60), or any other of that kind. I am downloading audio and video stream **seperatly** and then merge them using ffmpeg!

**Comment by psvks** [comment]
@Jopro1990 How are you doing that, can you give me an example?

**Comment by Jopro1990** [comment]
@psvks Sure, i posted the code as repostory, maybe we could work together to get a fixed, working version?

**Comment by psvks** [comment]
@Jopro1990 Welp thanks, and sure!

**Comment by Ali-Flt** [comment]
@pvks I have done the audio video merging as follows: 
```
def combine_video_audio(video_file, audio_file, output_file):
    video_stream = ffmpeg.input(video_file)
    audio_stream = ffmpeg.input(audio_file)
    ffmpeg.output(audio_stream, video_stream, output_file, acodec='copy', vcodec='copy', loglevel="quiet").run(overwrite_output=True)
```

input arguments are paths. If the input video is webm you need to change the output file extension to .mp4

**Comment by Ali-Flt** [comment]
@Jopro1990  How do you get higher than 1080p streams?

**Comment by JPMViana** [comment]
any solutions guys? someone could share the code with me?

**Comment by Ali-Flt** [comment]
@JPMViana what's your issue? I believe pytube has no issue showing 1080p. BTW maybe checkout [yt-dlp](https://github.com/yt-dlp/yt-dlp) which is a far more advanced and up to date tool for working with streaming services like YT.

**Comment by JPMViana** [comment]
@Ali-Flt Nice, thanks... about 1080p, i couldn't find something higher then 720p using pytube. are you sure that it is working?

**Comment by Ali-Flt** [comment]
@JPMViana what's the code you're using

**Comment by JPMViana** [comment]
@Ali-Flt just the function
```
 def download_video(url):
    yt = YouTube(url)
    for each in yt.streams.filter(adaptive=True, mime_type='video/webm'):
        print(each)
    #for each in yt.streams.filter(progressive=True).order_by('resolution').desc().first() 
        # print(each)
```

**Comment by webbster64** [comment]
it seems like its only giving a problem with 1080p60 I tested 2 videos one available in 1080p and the other one 1080p60 
the normal 1080p shows but the 1080p60 doesn't
