### ISSUE TITLE
[BUG] Exception while accessing title

### ISSUE THREAD

**Issue by RiRaggi** [pytube/pytube#1473]
PY Script:
-----------------------------------------------------------------------------------------------------

```
> file1 = open('YTVlist.txt', 'r')
> Urls = file1.readlines()
> file2 = open('YTVTitles.txt', 'w', encoding='utf-8')
> for line in Urls:
>     dummy = []
>     try:
>          yt = YouTube(line)
>     except VideoUnavailable:
>          print('Video {line} is unavaialable, skipping.')
>          file2.write('Video {line} is unavaialable, skipping.')
>     else:
>          print(YouTube(line).title + ";" + line)
>          dummy = YouTube(line).title
>          #TL = dummy.encode('utf-8')
>          file2.write(dummy + ";" + line)
```

------------------------------------------------------------------------------------------------------------

OUTPUT:

Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\pytube\__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ricca\Documents\PythonFiles\YouTube_Get_Title-Author.py", line 35, in <module>
    print(YouTube(line).title + ";" + line)
  File "C:\Python\Python310\lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=ZL44_lhJCPg. Please file a bug report at https://github.com/pytube/pytube

------------------------------------------------
pytube updated via GitHub for Windows
$ py -m pip install git+https://github.com/pytube/pytube

C:\Users\ricca\Documents\PythonFiles>py --version
Python 3.10.8

C:\Users\ricca\Documents\PythonFiles>pip install pytube
Requirement already satisfied: pytube in c:\python\python310\lib\site-packages (12.1.2)

C:\Users\ricca\Documents\PythonFiles>

**Comment by ypelech** [comment]
Got the same here: 
  File "c:\Utils\git\tools\toolsenv\Lib\site-packages\pytube\__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=e3-5YC_oHjE.

**Comment by AndrewwSSS** [comment]
I have got the same problem

**Comment by zeinovich** [comment]
Same

**Comment by tiagocborg** [comment]
I am also getting that error a lot. I am able to get around this with this little hack:

```
yt = YouTube(url)
while True:
    try:
        title = yt.title
        break
    except:
        print("Failed to get name. Retrying...")
        sleep(1)
        yt = YouTube(url)
        continue
 ```

**Comment by zeinovich** [comment]
It somehow fixed itself, didn't do nothing

**Comment by RiRaggi** [comment]
Hi ALL,
I solved the problem by using the YOUTUBE API directly on my Py Code

**Comment by Nefhara** [comment]
> Hi ALL, I solved the problem by using the YOUTUBE API directly on my Py Code

I have the same problem, do you have some part of code with your YOUTUBE API in your python script ?

Nota : I think the problem comes from the player function present in the "innertube.py" file (within pytube).
          Typical error message : "this video is unavailable" and from playererrormessage "watch on the latest version of youtube"

**Comment by glubsy** [comment]
> Nota : I think the problem comes from the player function present in the "innertube.py" file (within pytube). Typical error message : "this video is unavailable" and from playererrormessage "watch on the latest version of youtube"

The "watch on the latest version of youtube" is an error which has started occurring more and more recently and is most likely related to the client version advertised when making requests. It could also be due to some other parameter not being properly computed by the cipher module.

**Comment by DenJan123** [comment]
I have the same issue, adding a bit to code showed above this function helps with problem:
```
def retry_access_ty_object(url, max_retries=5, interval_secs=5, on_progress_callback=None):
    """
    Retries creating a YouTube object with the given URL and accessing its title several times
    with a given interval in seconds, until it succeeds or the maximum number of attempts is reached.
    If the object still cannot be created or the title cannot be accessed after the maximum number
    of attempts, the last exception is raised.
    """
    last_exception = None
    for i in range(max_retries):
        try:
            yt = YouTube(url, on_progress_callback=on_progress_callback)
            title = yt.title  # Access the title of the YouTube object.
            return yt  # Return the YouTube object if successful.
        except Exception as err:
            last_exception = err  # Keep track of the last exception raised.
            print(f"Failed to create YouTube object or access title. Retrying... ({i+1}/{max_retries})")
            time.sleep(interval_secs)  # Wait for the specified interval before retrying.

    # If the YouTube object still cannot be created or the title cannot be accessed after the maximum number of attempts, raise the last exception.
    raise last_exception
```

> I am also getting that error a lot. I am able to get around this with this little hack:
> 
> ```
> yt = YouTube(url)
> while True:
>     try:
>         title = yt.title
>         break
>     except:
>         print("Failed to get name. Retrying...")
>         sleep(1)
>         yt = YouTube(url)
>         continue
> ```

**Comment by RiRaggi** [comment]
@Nefhara @glubsy 
I published on my GitHub repository the python code, [searching YTV_Api](https://github.com/RiRaggi/YTV_API)

**Comment by Mazzzurrro** [comment]
```
def retry_access_ty_object(url, max_retries=5, interval_secs=5, on_progress_callback=None):
    """
    Retries creating a YouTube object with the given URL and accessing its title several times
    with a given interval in seconds, until it succeeds or the maximum number of attempts is reached.
    If the object still cannot be created or the title cannot be accessed after the maximum number
    of attempts, the last exception is raised.
    """
    last_exception = None
    for i in range(max_retries):
        try:
            yt = YouTube(url, on_progress_callback=on_progress_callback)
            title = yt.title  # Access the title of the YouTube object.
            return yt  # Return the YouTube object if successful.
        except Exception as err:
            last_exception = err  # Keep track of the last exception raised.
            print(f"Failed to create YouTube object or access title. Retrying... ({i+1}/{max_retries})")
            time.sleep(interval_secs)  # Wait for the specified interval before retrying.

    # If the YouTube object still cannot be created or the title cannot be accessed after the maximum number of attempts, raise the last exception.
    raise last_exception
```



This solution works, but within my aplication it's really slow. However, max_retries=100 and interval_secs=0.01 works for me, with the only issue of duplications which can be maintained with usage of exception. The problem persists also in Playlist() function, I managed to solve the issue with using this specific function in the playlist.py of pytube and few minor changes from:
```
def videos_generator(self):
    for url in self.video_urls:
        yield YouTube(url)
```
to:
```
def videos_generator(self):
    for url in self.video_urls:
        yield self.retry_access_ty_object(url)
```

**Comment by alexerhardt** [comment]
> I am also getting that error a lot. I am able to get around this with this little hack:
> 
> ```
> yt = YouTube(url)
> while True:
>     try:
>         title = yt.title
>         break
>     except:
>         print("Failed to get name. Retrying...")
>         sleep(1)
>         yt = YouTube(url)
>         continue
> ```

Have tried a variation of this, but it didn't work. Furthermore I've been throttled from downloading _any_ video, which didn't happen before (I would just skip through the ones that didn't have an accessible title)

If anyone has any clue on how to sort that would be appreciated.

**Comment by t-minski** [comment]
Why is this issue closed?

**Comment by opc241** [comment]
> Why is this issue closed?

I'm also wondering, cause i'm facing this issue too ... what is the proper solution now?

**Comment by Khanson00** [comment]
Same errors as everyone else. Did we ever find out why this is closed?? 

<img width="791" alt="Screenshot 2023-05-01 at 09 25 22" src="https://user-images.githubusercontent.com/34528017/235457815-f174041b-e7c7-438d-b121-a5df8b51ecc7.png">

**Comment by bnicholl** [comment]
I am also getting the same error

```
File "/Users/bennicholl/opt/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']

KeyError: 'videoDetails'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/var/folders/jk/zr1m5fps3zd762z2hjy2535m0000gn/T/ipykernel_580/1261415129.py", line 1, in <module>
    a.title

  File "/Users/bennicholl/opt/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(

PytubeError: Exception while accessing title of https://youtube.com/watch?v=JxnIkZU-oFE. Please file a bug report at https://github.com/pytube/pytube
```
Please re open this issue

**Comment by opc241** [comment]
@RiRaggi can you reopen the issue?

**Comment by RiRaggi** [comment]
@opc241 Done

**Comment by alexerhardt** [comment]
> Why is this issue closed?

I want to point out that this issue was probably one of the first, but also there is an ongoing explosion of new issues referring to this same problem - and many of them don't even have an issue title... 

The lack of the most basic etiquette is astounding. My sympathy to the maintainers first and foremost and to anyone earnestly attempting to help amidst the chaos.

**Comment by DenJan123** [comment]
As of now, this helps:
https://github.com/pytube/pytube/commit/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#diff-34b7de4e054a59b9c9a386a81fac050960951773737b50b5c8b746db6a364d47

**Comment by saulomonteirolimeira** [comment]
#sorted out
Try going to Pytube/innertube.py in line 78 change client = 'ANDRIOD' to client = 'WEB'

**Comment by PericoLedesma** [comment]
Same error just appear from nowhere. Open the issue

**Comment by ademidun** [comment]
`pytube.innertube._default_clients['ANDROID']=pytube.innertube._default_clients['WEB']`

Solution from @Shinku-Chen https://github.com/pytube/pytube/commit/c0d1aca42c4106e77ab4f8a0600737ea2ad27a96#commitcomment-111941588

**Comment by leo-capvano** [comment]
Hi, any update?

I am still facing the issue on an ec2-instance (but not on my laptop):

Traceback (most recent call last):
  File "/home/ubuntu/Youtube-Transcriptor/ytloader_venv/lib/python3.12/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Youtube-Transcriptor/ytloader_venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ubuntu/Youtube-Transcriptor/ytloader_venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ubuntu/Youtube-Transcriptor/app.py", line 16, in <module>
    video_transcription = transcript_video(yt_url, True, [video_lang], translation_lang)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Youtube-Transcriptor/src/youtube_svc.py", line 11, in transcript_video
    return loader.load()
           ^^^^^^^^^^^^^
  File "/home/ubuntu/Youtube-Transcriptor/ytloader_venv/lib/python3.12/site-packages/langchain_community/document_loaders/youtube.py", line 258, in load
    video_info = self._get_video_info()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Youtube-Transcriptor/ytloader_venv/lib/python3.12/site-packages/langchain_community/document_loaders/youtube.py", line 325, in _get_video_info
    "title": yt.title or "Unknown",
             ^^^^^^^^
  File "/home/ubuntu/Youtube-Transcriptor/ytloader_venv/lib/python3.12/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=v8-yeWXCsi4. Please file a bug report at https://github.com/pytube/pytube 

I also tried to change the client from 'ANDROID' to 'WEB' but nothing.

I am using pytube though Langchain's YoutubeLoader.

Can someone help me?
Thanks

**Comment by souravsahums** [comment]
I faced this issue while using YouTubeLoader of the langchain. It internally uses Pytube and it logged this issue. Package installed to the latest version [15.0.0]. Require help for the resolution.

**Comment by Shin0me** [comment]
In my case, the issue was fixed by replacing pytube with "pytubefix" in the program:

`from pytube import YouTube`
                       ↓↓↓
` from pytubefix import YouTube`
 
 Try to use pytubefix instead.
 

 You can learn in more detail from this url:
 [https://stackoverflow.com/questions/78160027/how-to-solve-http-error-400-bad-request-in-pytube](url)

**Comment by solovieff** [comment]
> Try to use pytubefix instead.

worked!
