### ISSUE TITLE
KeyError: 'assets'

### ISSUE THREAD

**Issue by SnoopiACK** [pytube/pytube#763]
python 3.8
pytube.__version__   --->  '9.6.4'

ERROR: 

  File "C:\Users\........\anaconda3\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]

KeyError: 'assets'

**Comment by StarkGang** [comment]
same problem here

**Comment by skoare** [comment]
You are using pytube3 and it hasn't been properly maintained for a long while now. Uninstall your current version and install directly from the original nficano/pytube repository.
```
pip uninstall pytube
pip install git+https://github.com/nficano/pytube.git
```

**Comment by AhmedSobhy01** [comment]
having same issue

**Comment by Bavop** [comment]
Same issue here

**Comment by yazilimfuryasi** [comment]
It seems that we all have the same problem :)

**Comment by giotsere** [comment]
This error happens sometimes,sometimes it does not. :|

**Comment by tfdahlin** [comment]
Looking into a fix for this now

**Comment by tfdahlin** [comment]
This seems to be an issue with YouTube returning incomplete responses some of the time.

Example successful response:
![image](https://user-images.githubusercontent.com/9667869/97054998-de3de800-1553-11eb-8b0c-e979b5a56091.png)


Example unsuccessful response:
![image](https://user-images.githubusercontent.com/9667869/97054261-7cc94980-1552-11eb-8a57-2655eb171f8a.png)

Not 100% sure this is something we can fix on the pytube side since this is extracted directly from the page HTML, but I'm going to look into it a bit more.

**Comment by AhmedSobhy01** [comment]
So I think I found a solution by just looping and passing exceptions until getting a successful response since probably the problem isn't from pytube side

```
while True:
    try :
        yt = YouTube(url)
        break
    except:
        pass
```

**Comment by tfdahlin** [comment]
@AhmedSobhy01 That's a temporary workaround that might work for your application in the meantime, but not something we can really implement into the library itself because it's not a real solution. I'm looking into other ways of fetching the necessary url right now, think I may have found something promising, just need to write + test it.

**Comment by VictorJosso** [comment]
> This error happens sometimes,sometimes it does not. :|

Same here

**Comment by a-czyrny** [comment]
I would recommend to throw a usefull exception to let the user implement a solution.

________________________________
Von: Victor Josso <notifications@github.com>
Gesendet: Saturday, October 24, 2020 1:29:40 AM
An: nficano/pytube <pytube@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [nficano/pytube] KeyError: 'assets' (#763)


This error happens sometimes,sometimes it does not. :|

Same here

**Comment by tfdahlin** [comment]
I found a solution for this particular KeyError problem, but it looks like the problem goes a bit deeper than just this part of the code. Working on something more robust right now.

**Comment by SnoopiACK** [comment]
> I found a solution for this particular KeyError problem, but it looks like the problem goes a bit deeper than just this part of the code. Working on something more robust right now.

Good look, keep us updated

**Comment by tfdahlin** [comment]
It might be a little while before this gets merged, so consider checking out my forked branch to test if it works for you -- I'm no longer running into problems with it, but would appreciate additional eyes with more use cases.

**Comment by AghnatHs** [comment]
same issue here,sometimes work sometimes dont,

**Comment by lcmeyer37** [comment]
Thank you @tfdahlin!

**Comment by nihaalnz** [comment]
Copied and pasted this extract.py, fixed the key error for me.

**Comment by z4na14** [comment]
Where can we see the "beta solution" for this problem? I want to try it myself if you say its fixed for you @tfdahlin so I can give feedback. Thanks for all the effort.

**Comment by tfdahlin** [comment]
@ElZanaorio the solution actually just got merged into this repo, so you should be able to give it a go with this repository now.

@RONNCC can you close this issue? It was solved by https://github.com/nficano/pytube/pull/767

**Comment by RONNCC** [comment]
Fixed by #767

**Comment by Fixazo** [comment]
Thanks for the fix !!

**Comment by tommeuh** [comment]
Thannnnks <3

**Comment by rajkarthy** [comment]
Quick fix,  change (Alternate solution)
```
def js_url(html: str) -> str:
   base_js = re.search("\/s\/player.*\/base\.js", html).group()
   return "https://youtube.com" + base_js
```

**Comment by RONNCC** [comment]
@rajkarthy  what is the context?

**Comment by tfdahlin** [comment]
@RONNCC I think @rajkarthy is offering another solution to the one that got merged, and didn't realize this issue was already fixed

**Comment by rajkarthy** [comment]
@RONNCC @tfdahlin Yes its an alternative with a small change

**Comment by RONNCC** [comment]
@rajkarthy  feel free to submit a PR if there is benefit :)

**Comment by klaymond** [comment]
Is this already on Pypi? I just pip installed latest version and I am still getting the issue. Do I have to build from source?

**Comment by tfdahlin** [comment]
@klaymond this is not on pypi currently, and I believe the pypi package is broken. We're trying to get the repo owner to update the pypi package, but in the meantime, you can use `python -m pip install git+https://github.com/nficano/pytube` to install the most up-to-date version.

**Comment by klaymond** [comment]
Thanks!

**Comment by RONNCC** [comment]
@klaymond  I just managed to update PyPi (wasn't working before) -- should work now

**Comment by abhijeetpujara** [comment]
[https://github.com/abhijeetpujara/Images/blob/master/error1.png](url)  this is my code 

and this is what I get an error 
[https://github.com/abhijeetpujara/Images/blob/master/error2.png](url)
